#!/usr/bin/env python3
import math

if __name__ == "__main__":
	print("#include <stddef.h>")
	print("//this file is autogenerated by generate_table.py\n")
	print("static const uint64_t LOG2_LOOKUP[2048] = { 0,")
	for i in range(1, 2048):
		print("%d," % -int(math.log2(i/2048.) * 2048))
	print("};")
