#pragma once
#include "lzma_state.h"
#include "packet_slab.h"
#include <stddef.h>

//todo: this explination sucks
//this structure stores a list of undo states. this is generated by the slab neighbour generator and can be used to return to the last slab if it is not suitable

typedef struct {
	size_t position;
	LZMAPacket old_packet;
} PacketSlabUndo;

typedef struct PacketSlabUndoHeap_struct PacketSlabUndoHeap;

#define UNDO_STACK_SIZE 8
typedef struct {
	size_t total_count;
	size_t count;
	PacketSlabUndo stack[UNDO_STACK_SIZE];
	PacketSlabUndoHeap* last;
} PacketSlabUndoStack;

void packet_slab_undo_stack_new(PacketSlabUndoStack* undo_stack);
void packet_slab_undo_stack_free(PacketSlabUndoStack* undo_stack);

void packet_slab_undo_stack_insert(PacketSlabUndoStack* undo_stack, PacketSlabUndo undo);
void packet_slab_undo_stack_apply(PacketSlabUndoStack* undo_stack, PacketSlab* slab);
size_t packet_slab_undo_stack_count(const PacketSlabUndoStack* undo_stack);
